version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENV=production
      - NODE_ENV=development
      - PORT=8080
      - USERPOOL_ID=us-east-1_NsXzMDlGr
    ports:
      - "8080:8080"